// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// waterbalance
NumericVector waterbalance(NumericVector calvals, NumericMatrix data);
RcppExport SEXP DCWBM_waterbalance(SEXP calvalsSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type calvals(calvalsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    __result = Rcpp::wrap(waterbalance(calvals, data));
    return __result;
END_RCPP
}
